sudo: required
language: r
warnings_are_errors: false
dist: trusty

# enable RELEASE_CANDIDATE to run (slow & fragile) tests of sampler validity before releases
env:
  global:
    - RELEASE_CANDIDATE=false
    - LINTR_COMMENT_BOT=false
    - secure: oGQdnwab0SbOxIh8xg0PSlqPP7e+rDdKfKZmZ5FGyawc9hHH5KZ9XfQnk+z0LTQXWGHTJLHoWT4CmNBh6w9LLbwaaZi/KWeJVQ5hA9PM0HRchG8KDX0J1BIOKAx5ymBZjHgIhRZob8bi7V3QwtUO3mcgYa5OwSvNABFqwQbvWnwCLgILZchZnPW/MIgUP/nBcrT/FfzB4fyM1wLNBbz0KWiIw6IAj0YFV3kPY82DAMRuJwsI5HMlv+z9/OELpwgkwU22Oru+N2VpIdToBI9lOfblCHl4Sn4tgTqV1NooIz/4XSeLbQdcrulfFo8y5yKjnYdIxdXnctDm5ixRnNpa8+0EAZYy2IBu0PlJH6QfnYfT6EbMyF0j7c8wRh2CbWM/35aNKrZcpchuxcKuRcP0n4eNnb64qOTSj9o1mFu9GXjqwr+MiRXUdOcy4r4WiEguHNVcsW1ct3C7XAU0Bv4RE5/IToqOGUUnYlJiWIroIVg5UPG+r4j4psyh4nySuruq0/1Ac/QVfy/P9RP+JuaWahiImiydS/Rsz34vxF69QxDiW8Oe5e1cSeHw3fqQeDSB2TTiidWZ3u97+0wa3wP5DN8TilyUG3KjHlfjMCousnk8LtGUWtpEzxe8KbBlakNWETJwVYa3rCQ/H+bTiUq9CrIJTDg7A4BTuHB0bCSpAdE=

# these are dependencies of suggested packages for which there are binaries,
# add them here to try to reduce installation time
r_binary_packages:
  - abind
  - coda
  - codetools
  - colorspace
  - DBI
  - digest
  - foreign
  - ggplot2
  - inline
  - lattice
  - MASS
  - MCMCpack
  - mgcv
  - mvtnorm
  - nlme
  - plyr
  - Rcpp
  - rpart
  - rstan
  - stringr
  - survival
  - XML

r_packages:
  - reticulate
  - tensorflow
  - R6
  - testthat
  - covr
  - DiagrammeR
  - knitr
  - rmarkdown
  - rsvg
  - bayesplot
  - extraDistr
  - devtools
  - tidyverse
  - lintr

r_github_packages:
  - rich-iannone/DiagrammeRsvg

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    sources:
      ubuntu-toolchain-r-test
    packages:
      - libmagick++-dev
      - wget
      - libatlas3gf-base
      - libatlas-dev
      - python-joblib
      - python-dev
      - libv8-dev

before_install:
  - pip install --user numpy
  - pip install --user scipy
  - pip install --user 'tensorflow==1.10'
  - pip install --user 'tensorflow-probability'

after_success:
  - Rscript -e "covr::codecov()"
  - Rscript -e "lintr::lint_package()"

email:
  on_success: change
  on_failure: change
